### ISSUE TITLE
Missing of .htaccess rewrite url file

### ISSUE THREAD

**Issue by iXo** [HuasoFoundries/phppgadmin#24]
Hello,

I found your fork from the official phpPgAdmin github, and wanted to try your fork as I need a version compatible with PG 9.6.

But I can't make it works, as the /tree/* or /redirect/* urls don't work. I found that the index.php have function that will process these 'virtual' path.

But to make the url forwarded to index.php, the web server need to have instructions on how to do so.
For apache, the .htaccess file must be created with the good content.

As you don't seems to provide any .htaccess file, and that file like install are not up to date, I think you could provide a basic rewrite url .htaccess file.

Thanks.

**Comment by amenadiel** [comment]
That's a very good point! As I have been an nginx user for the last 7 years I totally forgot about apache.

However, the rules for apache are the same as for any Slim Framework 3.0 app.

Until I add a proper .htaccess file, I reccomend you to use this instructions: [Slim -> WebServers](https://www.slimframework.com/docs/start/web-servers.html)

**Comment by iXo** [comment]
Ok, thanks, I didn't know that the app was converted to Slim framework.
