### ISSUE TITLE
/tree path lead to a 404 error

### ISSUE THREAD

**Issue by iXo** [HuasoFoundries/phppgadmin#25]
Hello,

I am using you version of phpPgAdmin, and after the creation of the .htaccess rule, I am testing it.

I am using php 5.8 with wampserver (on windows) and the refresh button, that is using a call on /tree/browser will replace the left menu with a page not found error.

**Comment by amenadiel** [comment]
You're right, there was a link I forgot to replace. Please upgrade to beta 3.

**Comment by iXo** [comment]
Fixed, indeed.

Thanks for all your hard work on keeping this software alive. With the need PgAdmin 4, phpPgAdmin is really important !
