### ISSUE TITLE
Call to member function getContainer() on null

### ISSUE THREAD

**Issue by iXo** [HuasoFoundries/phppgadmin#26]
Hello,

I am trying to use your phpPgAdmin with wampserver (php v5.8) and after using the .htaccess file for Slim server, the login button will leave me with a blank page and this error log trace :

[Mon Jan 30 06:29:12 2017] PHP Fatal error:  Call to a member function getContainer() on null in C:\rdd\programs\phppgadmin\htdocs\src\classes\Misc.php on line 197

I can help for testing if you need.

**Comment by amenadiel** [comment]
Ok great, you broke it!

Nah, just kidding. I've just fixed that issue in the just released beta 3, please upgrade.

Heads up though, to have passed through Misc.php line 197 you must have `extra_login_security` set to true in your config, and try to login using usernames like *root*, *postgres*, *administrator* or *pgsql*.

**Comment by iXo** [comment]
Thanks ! Everything seems to works fine now.

(And yes I was trying to login in using postgres username with extra_login_security set to true)
