### ISSUE TITLE
Questions marks help links will open a 404 error page

### ISSUE THREAD

**Issue by iXo** [HuasoFoundries/phppgadmin#27]
I tried some few links (schema, databse, views and M views) they all want to open a .html help file in the src folder.

For the database help link it wants to open the src/views/ddl-schemas.html file, but in the src/views folder there are only .php files, and no ddl* file either.

**Comment by amenadiel** [comment]
OK. Long story short, the help files aren't actually in this repo. They are just links to Postgres doc on each topic. It is the base url that was missing and made them look as local references.

I have restored the base url. It was read from a global scope that isn't there in my version, so I had to inject the conf to the constructor to pass the context without resorting to global variables.

Please upgrade to the freshly released beta 4

**Comment by iXo** [comment]
Hi, I have tried the beta 4, and I can confirm the 404 error is gone, but the help page is always displaying "Invalid help page" (ie: tested url when clicked on the "Views" question mark : http://192.165.10.205/src/views/help.php?help=pg.view&server=%3A5432%3Aallow)

**Comment by amenadiel** [comment]
It should redirect you to https://www.postgresql.org/docs/9.6/static/tutorial-views.html

Where is it redirecting you to?
