### ISSUE TITLE
Composer warning with installation

### ISSUE THREAD

**Issue by vaibhav-kaushal** [HuasoFoundries/phppgadmin#31]
I am getting this warning when I run composer update after downloading the zipball: 
```
package raveren/kint is abandoned, you should avoid using it. Use kint-php/kint instead.
```
Shouldn't we update? Are there any issues?

**Comment by amenadiel** [comment]
It's true. raveren/kint was abandoned. However, these kind of warnings are only a reccomendation and not an error.

Anyway, I replaced Kint with the new package in release beta 11
